name: GitHub Stats Update

on:
  schedule:
    - cron: "0 * * * *" # Atualiza a cada hora, você pode modificar o cronograma
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate stats images
        run: |
          # Substitua com o seu nome de usuário e token do GitHub
          curl -o github_stats.png "https://github-readme-stats.vercel.app/api?username=RaphaelDias&show_icons=true&theme=radical&count_private=true&token=${{ secrets.TOKEN }}"
          curl -o top_languages.png "https://github-readme-stats.vercel.app/api/top-langs/?username=RaphaelDias&layout=compact&theme=radical&count_private=true&token=${{ secrets.TOKEN }}"

      - name: Commit and push stats to README
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add github_stats.png top_languages.png
          git commit -m "Atualizar estatísticas do GitHub"
          git push
