name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.git_token }}
        run: |
          curl -o github_stats.svg "https://github-readme-stats.vercel.app/api?username=Raphael345&show_icons=true&count_private=true&theme=radical&hide_border=true&token=${{ secrets.git_token }}"
          curl -o top_languages.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=Raphael345&layout=compact&theme=radical&count_private=true&hide_border=true&token=${{ secrets.git_token }}"
          convert github_stats.svg github_stats.png
          convert top_languages.svg top_languages.png

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add github_stats.png top_languages.png
          git commit -m "Atualizar estatísticas do GitHub" || echo "Nada para commit"
          git push
